mbti:
  repository:
    mysql:
      entity:
        datasource:
          jdbcUrl: jdbc:mysql://localhost:13306/mbti?allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
          data: classpath:import.sql
        jpa:
          hibernate:
            ddl-auto: update
          properties:
            hibernate:
              format_sql: true

logging:
  level:
    sql: debug